# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEUY_kuC5tlSdTXj-jesa-sMFMhhebIh
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt

# Set page title
st.set_page_config(page_title="Model Prediction App", layout="wide")

st.title("📈 Model Prediction & Equation Analysis")

# Sidebar for configuration
st.sidebar.header("Configuration")
model_file = "trained_model.joblib"

# 1. Load the Model
@st.cache_resource
def load_model(path):
    try:
        return joblib.load(path)
    except Exception as e:
        return None, str(e)

model_result = load_model(model_file)

if isinstance(model_result, tuple):
    st.sidebar.error(f"Error loading model: {model_result[1]}")
    model = None
else:
    model = model_result
    st.sidebar.success("Model loaded successfully!")

# 2. Define the Range
st.sidebar.subheader("Iteration Settings")
start_val = st.sidebar.number_input("Start Value", value=1)
end_val = st.sidebar.number_input("End Value", value=300)

# 3. Predict Logic
if st.button("Generate Predictions"):
    # Create the range of X values
    x_values = np.arange(start_val, end_val + 1)

    # Calculation based on the manual equation provided:
    # y = (2/3) * x + (8/9 + 1)
    m = 2/3
    c = (8/9) + 1
    y_equation = m * x_values + c

    results_df = pd.DataFrame({
        'X': x_values,
        'Equation_Y': y_equation
    })

    # If the model is available, use it to predict
    if model:
        try:
            # Preparing input for the model (assuming it expects a DataFrame or 2D array)
            # Adjust the column name 'X' if your model expects a different name
            X_input = pd.DataFrame({'X': x_values})
            results_df['Model_Prediction'] = model.predict(X_input)
        except Exception as e:
            st.warning(f"Model prediction failed: {e}. Showing equation results only.")

    # 4. Display Results
    col1, col2 = st.columns([1, 2])

    with col1:
        st.subheader("Data Table")
        st.dataframe(results_df, height=400)

    with col2:
        st.subheader("Visual Analysis")
        fig, ax = plt.subplots(figsize=(10, 5))
        ax.plot(results_df['X'], results_df['Equation_Y'], label='Equation: y = (2/3)x + 1.89', color='blue', linestyle='--')

        if 'Model_Prediction' in results_df.columns:
            ax.scatter(results_df['X'], results_df['Model_Prediction'], label='Model Predictions', color='red', s=10, alpha=0.5)

        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        ax.legend()
        ax.grid(True)
        st.pyplot(fig)

    # 5. Download results
    csv = results_df.to_csv(index=False).encode('utf-8')
    st.download_button(
        label="Download Predictions as CSV",
        data=csv,
        file_name='predictions.csv',
        mime='text/csv',
    )
else:
    st.info("Adjust the range in the sidebar and click 'Generate Predictions' to see the results.")